<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Page Object Model" duration-ms="217" started-at="2018-09-20T19:51:14 IST" finished-at="2018-09-20T19:51:14 IST">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="217" started-at="2018-09-20T19:51:14 IST" finished-at="2018-09-20T19:51:14 IST">
      <class name="testcases.LoginTest">
        <test-method status="SKIP" signature="loginTest()[pri:0, instance:testcases.LoginTest@74eb909f]" name="loginTest" duration-ms="9" started-at="2018-09-20T19:51:14 IST" finished-at="2018-09-20T19:51:14 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test LOGINTEST as the run mode is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test LOGINTEST as the run mode is NO
at listeners.CustomListener.onTestStart(CustomListener.java:14)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:69)
at org.testng.internal.Invoker.runTestResultListener(Invoker.java:1516)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:631)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginTest@74eb909f]" name="tearDown" is-config="true" duration-ms="89" started-at="2018-09-20T19:51:14 IST" finished-at="2018-09-20T19:51:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Login Test -->
  </suite> <!-- Page Object Model -->
</testng-results>
